beast_jar: lib/feast.jar
seed: 1
n_taxa: 10
min_pop_size: 1000
max_pop_size: 2000
sampling_window: 100
sequence_length: 20
relaxed_clock: False
mutation_rate: 3.0
kappa: 2.0
frequencies: [0.25, 0.25, 0.25, 0.25]
rate_sd: null
chain_length: 1000000
log_every: 1000
prior_params:
  clock_rate: { m: 1.0, s: 1.25 }
  pop_size: { m: 1.0, s: 1.25 }
  kappa: { m: 1.0, s: 1.25 }
init_values: { clock_rate: 1.0, pop_size: 1.0, kappa: 2.0 }
estimate_topology: False
n_iter: 5
inference: mean_field
