beast_jar: lib/feast.jar
lsd_executable: lsd
relaxed_clock: False
mutation_rate: 0.0005
rate_sd: null
chain_length: 1000000
log_every: 1000
estimate_clock_rate: False
prior_params:
  pop_size: { m: 2 , s: 2 }
  kappa: { m: 1.0, s: 1.25 }
init_values: { clock_rate: 1.0, pop_size: 10, kappa: 2.0 }
estimate_topology: True
n_iter: 30000
inference: mean_field
burn_in: 0.1
n_runs: 100
out_dir: out-data
datasets:
  dengue: Dengue.env.nex
  rsv2: RSV2.nex
seed: 1
